version: "3.8"

volumes:
  postgres:
  api:

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "49200:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  api:
    build:
      context: ../dicomweb-pacs-api
    depends_on:
      - postgres
    volumes:
      - ./.data/api/uploads:/app/uploads
    ports:
      - "49201:3000"
    environment:
      LOG_LEVEL: debug
      LOG_TEXTLOGGING: "true"
      PORT: 3000
      DB_ADDR: postgres:5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres
      ENABLE_CORS: "true"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s

  react:
    stdin_open: true
    build:
      context: ../dicomweb-pacs-front
    volumes:
      - ../dicomweb-pacs-front:/root
    ports:
      - "49202:4000"

  postgres:
    image: postgres:13
    restart: unless-stopped
    ports:
      - "49203:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres